[package]
name = "hyprKCS"
version = "1.16.2"
edition = "2021"
license = "MIT"

[dependencies]
gtk4 = { version = "0.10.3", features = ["v4_12"] }
libadwaita = "0.8.1"
regex = { version = "1.12.2", default-features = false, features = ["perf", "std", "unicode-perl"] }
dirs = "6.0.0"
anyhow = "1.0.100"
once_cell = "1.21.3"
gtk4-layer-shell = "0.7.1"
clap = { version = "4.5.54", features = ["cargo", "derive"] }
fuzzy-matcher = "0.3.7"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[[bin]]
name = "hyprKCS"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = "thin"
codegen-units = 16
strip = true
panic = "abort"
