[package]
name = "hyprKCS"
version = "1.7.0"
edition = "2021"
license = "MIT"

[dependencies]
gtk4 = { version = "0.10.3", features = ["v4_12"] }
libadwaita = "0.8.1"
regex = "1.12.2"
dirs = "6.0.0"
anyhow = "1.0.100"
once_cell = "1.21.3"
gtk4-layer-shell = "0.7.1"
clap = { version = "4.5.54", features = ["derive"] }
comfy-table = "7.2.1"
fuzzy-matcher = "0.3.7"
chrono = "0.4.42"

[[bin]]
name = "hyprKCS"
path = "src/main.rs"
