[package]
name = "hyprKCS"
version = "1.2.0"
edition = "2021"
license = "MIT"

[dependencies]
gtk4 = "0.10.3"
libadwaita = "0.8.1"
regex = "1.12.2"
dirs = "6.0.0"
anyhow = "1.0.100"
once_cell = "1.21.3"

[[bin]]
name = "hyprKCS"
path = "src/main.rs"